version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: wget -O yarn.js https://github.com/yarnpkg/yarn/releases/download/v1.6.0/yarn-1.6.0.js
      - run: node ./yarn.js --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: node ./yarn.js run test:report
      - store_artifacts:
          path: coverage
          prefix: coverage
      - run: node ./yarn.js build
      - run:
          command: node ./yarn.js run semantic-release
          environment:
            ASSETS: lib